### ISSUE TITLE
Error in checkmate::assert_numeric(img, lower = 0) : 

### ISSUE THREAD

**Issue by cb12ag** [rorynolan/nandb#7]
> dim(my_img)
[1] 1024 1024    1 6338

> display( detrendr::mean_pillars( autothresholdr::mean_stack_thresh(my_img[, , 1, ], "h") ) )
Error in checkmate::assert_numeric(img, lower = 0) : 
  long vectors not supported yet: ../../src/include/Rinlinedfuns.h:537

> plot_tbl <- tibble(
  frame = seq_len(dim(my_img)[4]),
  channel1 = apply(autothresholdr::mean_stack_thresh(my_img[, , 1, ], "h"), 4, 
                   mean, na.rm = TRUE)
) %>% gather(ch, mean, -frame)
Error in checkmate::assert_numeric(img, lower = 0) : 
  long vectors not supported yet: ../../src/include/Rinlinedfuns.h:537

> my_brightness_img <- brightness(my_img, def="e", thresh="Huang", detrend=TRUE) 
Error in checkmate::assert_numeric(img, lower = 0) : 
  long vectors not supported yet: ../../src/include/Rinlinedfuns.h:537

**Comment by rorynolan** [comment]
This stems from a problem in the checkmate package. I have submitted a pull request containing a fix there https://github.com/mllg/checkmate/pull/231. Until that is accepted, as a work around, you could do remotes::install_github("rorynolan/checkmate") to get my patched checkmate. Please try that and tell me how it goes.
